### PR TITLE
buildmaster: allow custom repository parameter for openvpn force schedulers

### PR DESCRIPTION
**Pull request by uddr**
This allows to run force schedulers for Gerrit patchsets.

### CODE REVIEW

**Comment by mattock** [comment]
This was a new feature to me, so I had to check the [documentation](https://docs.buildbot.net/latest/manual/configuration/schedulers.html) to understand what it does.

I think it makes sense to be able to override the repository URL as you can already override branch and revision. I would suggest, though, making the repository URL overrideable for "openvpn-release", "openvpn-main" and "ovpn-dco" schedules as well for the sake of consistency.

**Review by mattock — CHANGES_REQUESTED** [review]
This was a new feature to me, so I had to check the [documentation](https://docs.buildbot.net/latest/manual/configuration/schedulers.html) to understand what it does.

I think it makes sense to be able to override the repository URL as you can already override branch and revision.

I would suggest, though, making the repository URL overrideable for "openvpn-release", "openvpn-main" and "ovpn-dco" schedules as well for the sake of consistency.

**Review by mattock — APPROVED** [review]

**Comment by uddr** [comment]
> This was a new feature to me, so I had to check the [documentation](https://docs.buildbot.net/latest/manual/configuration/schedulers.html) to understand what it does.
> 
> I think it makes sense to be able to override the repository URL as you can already override branch and revision.
> 
> I would suggest, though, making the repository URL overrideable for "openvpn-release", "openvpn-main" and "ovpn-dco" schedules as well for the sake of consistency.

@mattock  yeah it makes sense, updated

**Comment by mattock** [comment]
Thanks @uddr ! I just realized that I can actually make use of the openvpn-main force scheduler now to test my own changes after running them through my own buildbot (which only has the dockerized Linux workers).

**Review by flichtenheld — APPROVED** [review]

**Pull request merged**
